// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbx0kz7L2dPW-eeoYmetjnGHbs3Aj5xA',
    appId: '1:413974801864:android:2850644ee9b3c43c0ba4fd',
    messagingSenderId: '413974801864',
    projectId: 'eptechnology-54e58',
    storageBucket: 'eptechnology-54e58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8dyXRJlYseefcfipmm8gCbGJBf1Wfedk',
    appId: '1:413974801864:ios:7830538c727813150ba4fd',
    messagingSenderId: '413974801864',
    projectId: 'eptechnology-54e58',
    storageBucket: 'eptechnology-54e58.appspot.com',
    androidClientId: '413974801864-aajn8b2qli9crjkfu0g1buijqh0pvtgh.apps.googleusercontent.com',
    iosClientId: '413974801864-ncbifniu90h8vliue0vobhal21888l1g.apps.googleusercontent.com',
    iosBundleId: 'com.nylo.ios',
  );
}
